version: "3.9"

services:
  web:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      DATA_DIR: /app/data
    volumes:
      - /data/epstein:/app/data:ro
      - ./backend/media:/app/backend/media
      - ./backend/static:/app/backend/static
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
    ports:
      - "8000:8000"
